services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/frontend
    ports:
      - "3000:3000"
    networks:
      - dev-net

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/backend
    ports:
      - "5000:5000"
    networks:
      - dev-net
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
networks:
  dev-net:
    driver: bridge
