services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    networks:
      - dev-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
