services:
  # frontend:
  #   build:
  #     context: ./frontend/
  #   volumes:
  #     - ./frontend:/usr/app/
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - dev-net

  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend:/usr/app/
    ports:
      - "5000:8000"
    networks:
      - dev-net
    environment:
      - PORT=8000

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - ./database:/var/lib/postgresql/data
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
