services:
  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/usr/app/
    ports:
      - "3000:3000"
    networks:
      - dev-net

  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend:/usr/app/ # Mount your local code into the container
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - dev-net
    command: ["go", "run", "."] # Run the app without rebuilding the image

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
