services:
  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/usr/app/
    ports:
      - "3000:3000"
    networks:
      - dev-net

  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend:/usr/app/
    ports:
      - "5000:8000"
    networks:
      - dev-net
    environment:
      - PORT=8000
networks:
  dev-net:
    driver: bridge
